### ISSUE TITLE
p师傅，折腾了一天了，build的时候一直报错

### ISSUE THREAD

**Issue by Raul1718** [phith0n/vulhub#4]
测试supervisor环境的时候，docker-compose build

然后开始下载，随后就报错：

ERROR: Service 'web' failed to build: unauthorized: authentication required

**Comment by phith0n** [comment]
执行
```
docker -v
docker-compose -v
```

查看你docker和docker-compose的版本，是否是这个导致 https://github.com/docker/compose/issues/1622
并确认你之前没有连接过其他私有仓库。
vulhub/*都是公开的镜像，不应该存在unauthorized的问题

**Comment by Raul1718** [comment]
解决了，应该是因为之前连接过其他的私有仓库的问题。
kill掉之前的container，再重新docker-compose build 
supervisor的服务就ok了。
