### ISSUE TITLE
php_xxe

### ISSUE THREAD

**Issue by idlefire** [phith0n/vulhub#5]
ERROR: Service 'apache' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y gcc wget' returned a non-zero code: 100
每次到执行 apt-get update 就开始超时...vps 是国外的,,,
求P师傅解答...😅

**Comment by phith0n** [comment]
不清楚。。这种情况和我这个项目没关系，你可以手动尝试一下：

```
docker run -it --rm php:apache bash
apt-get update
apt-get install -y gcc wget
```

**Comment by idlefire** [comment]
谢谢P师傅 通过修改Dockerfile解决了 我在apt-get update之前添加了http_proxy

**Comment by leveryd** [comment]
这个ubuntu默认的源，访问真的是太慢了。卡死不动。
